# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    #npm run build
    #npm run test
  displayName: 'npm install and build'
  
- script: |
    npm run unittests
  displayName: 'Run unit tests'

- script: |
    npm run uitests
  displayName: 'Run UI tests'

- script: |
    which go
    # Install dep
    sudo mkdir /home/vsts/go/bin
    curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
    #sudo add-apt-repository ppa:longsleep/golang-backports
    #sudo apt-get update
    #sudo apt-get -y install golang-go
    #export GOPATH=$(pwd)
    git clone https://github.com/monch1962/wilee
    cd wilee
    dep ensure
    make local
  displayName: 'Run wilee API tests'
