# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install and build'
  
- script: |
    # First gather lines-of-coverage data from the test cases
    node_modules/nyc/bin/nyc.js --reporter=lcov --reporter=text-lcov npm test

    # Download sonar-scanner
    SONARCLOUDDIR=/tmp
    wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-3.2.0.1227-linux.zip -O $SONARCLOUDDIR/sonar.zip
    unzip $SONARCLOUDDIR/sonar.zip -d /tmp

    # Print out some diagnostic info
    ls -al $SONARCLOUDDIR
    cat $SONARCLOUDDIR/sonar-scanner-3.2.0.1227-linux/conf/sonar-scanner.properties
    PATH=$SONARCLOUDDIR/sonar-scanner-3.2.0.1227-linux/bin:$PATH
    echo $PATH
    APP_DIR=$(pwd)
    ls -al
    sonar-scanner -h

    # Run sonar-scanner
    sonar-scanner \
    -Dsonar.projectKey=monch1962_hello-world-devops \
    -Dsonar.organization=monch1962-github \
    -Dsonar.sources=. \
    -Dsonar.exclusions=node_modules/**,test/**,coverage/** \
    -Dsonar.host.url=https://sonarcloud.io \
    -Dsonar.javascript.lcov.reportPaths=app/coverage/** \
    -Dsonar.login=8725538bd2603c6990da57d9c53afe2d176fb844
  displayName: 'Run sonarcloud code quality tests'
    
- script: |
    npm run unittests
  displayName: 'Run unit tests'

- script: |
    # Install the testcafe framework; we're going to use it for UI testing
    npm install -g testcafe

    # Start the app running, and save the PID
    node helloworld.js &
    APP_PID=$!

    #npm run uitests
    testcafe "chrome:headless" test/ui/helloworld.ts

    # Kill the app
    kill $APP_PID
  displayName: 'Run UI tests'

- script: |
    # Start the app running and save the PID
    node helloworld.js &
    APP_PID=$!

    # Grab a copy of wilee (you'd probably want to get it from somewhere like Artefactory or Nexus...)
    wget https://www.dropbox.com/s/sthv0p77c5gip2g/wilee?dl=0 -O wilee
    chmod +x wilee
    ls -l wilee

    # Run all API tests in test/api/*.wilee.json
    APP=http://localhost:8080 TESTCASES=test/api/*.wilee.json ./wilee

    # If wilee fails with errors, kill the app instance and exit 1 so Devops can see the failure
    if [ $? -ne 0 ]; then kill $APP_PID && exit 1; fi

    # Don't need the app any more; kill it
    kill $APP_PID

    # Let's display the summary of the integration test results
    TESTRESULTS=$(cat test/api/*.result.json)
    echo $TESTRESULTS | jq '.'
    echo $TESTRESULTS | jq 'del(.request, .expect, .actual)'

    # If there's any failed test cases, then exit 1 so Devops can see the failure
    FAILED_TESTS=$(echo $TESTRESULTS | jq '.pass_fail' | grep fail | wc -l)
    if [ $FAILED_TESTS -gt 0 ]; then echo $FAILED_TESTS "API tests failed" && exit 1; fi
  displayName: 'Run wilee API tests'

- script: |
    # Now start the app running, and capture the PID so we can kill it later
    # Note that we're setting HTTP_PROXY to point to the Hoverfly stub, which we'll start next
    HTTP_PROXY=http://localhost:8500 node helloworld.js &
    APP_PID=$!

    # Get the hoverfly stub engine
    wget https://github.com/SpectoLabs/hoverfly/releases/download/v0.17.7/hoverfly_bundle_linux_amd64.zip -O hoverfly.zip
    unzip hoverfly.zip

    # Start hoverfly running, and read in the stub config. In this case we're going to stub out 
    # the (fictional) trumpwall.com site
    ./hoverctl start
    ./hoverctl import test/integration/stub-definitions/trumpwall.com.stub.json

    # Run the stubbed integration tests
    npm run integrationtests
    if [ $? -ne 0 ]; then kill $APP_PID && ./hoverctl stop && exit 1; fi

    # Stop Hoverfly
    ./hoverctl stop

    # Kill the app
    kill $APP_PID
  displayName: 'Run integration tests (against stubbed backend)'

- script: |
    # Start the app running, and capture the PID so we can kill it later
    node helloworld.js &
    APP_PID=$!

    # Install the artillery load testing tool
    npm install -g axe-cli
    axe --help

    # Run the Axe accessibility tests (if there's more pages to test, just give it a comma-separated list of URLs)
    axe http://localhost:8080

    # Kill the app
    kill $APP_PID
  displayName: 'Run Axe accessibility tests'
  
- script: |
    # Start the app running, and capture the PID so we can kill it later
    node helloworld.js &
    APP_PID=$!

    # Install the artillery load testing tool
    npm install -g artillery
    artillery -V

    # Run the artillery load test
    artillery run test/performance/performance.yml

    # Kill the app
    kill $APP_PID
  displayName: 'Run Artillery performance test'
